Added copy password feature
thekatze/rehash pull request #34
Opened 2023-03-30 16:55 UTC by tarunsamanta2k20

Allow copying password from detail page #33

#33 

i added it on the detailed page i found this component from route list.

https://user-images.githubusercontent.com/55488549/228909303-62f85bf1-e845-49aa-8c60-c121663bc1bd.mp4

2023-03-31 16:04 UTC, tarunsamanta2k20 commented
@thekatze any changes require?

Don't close the PR. Ask me for the changes.

2023-04-03 15:13 UTC, thekatze requested changes

2023-04-03 15:13 UTC, thekatze commented on apps/app/src/components/UnlockStore.tsx
this is the wrong file: as i stated in [the issue](https://github.com/thekatze/rehash/issues/33) it should be added in the file `apps/app/src/pages/EditEntry.tsx`

2023-04-03 15:13 UTC, thekatze commented on apps/app/src/components/UnlockStore.tsx
> +            } } />
formatting

enabling the `format on save` setting in visual studio code will make your code look much nicer :)

2023-04-03 15:13 UTC, thekatze commented on apps/app/src/components/UnlockStore.tsx
> +        <HStack  spacing="24px" justifyContent="flex-end">
formatting (double space)
```suggestion
        <HStack spacing="24px" justifyContent="flex-end">
```

2023-04-03 15:46 UTC, thekatze commented on apps/app/src/components/UnlockStore.tsx
> +        <HStack  spacing="24px" justifyContent="flex-end">
also, ive been using hope-ui variables for spacings: using something like `$4` instead of `24px` would make the code more consistent

2023-04-03 23:42 UTC, tarunsamanta2k20 commented
@thekatze please check vercel log once. i was working fine before [Merge branch 'main' into tarun_samanta/](https://github.com/thekatze/rehash/pull/34/commits/6e0a285cc94073d8124e3ae29032f66959ab89d4)https://github.com/thekatze/rehash/issues/33. you may check deployment logs once let me konw what's wrong!!.

2023-04-04 19:54 UTC, thekatze commented
build fails because there have been changes to the useI18n hook.
the `t` function changed:
before it was `t()("TRANSLATION_KEY")`
now it is the simpler `t("TRANSLATION_KEY")`

2023-04-04 20:06 UTC, tarunsamanta2k20 commented
> build fails because there have been changes to the useI18n hook. the `t` function changed: before it was `t()("TRANSLATION_KEY")` now it is the simpler `t("TRANSLATION_KEY")`

@thekatze done!!.

2023-04-04 21:34 UTC, thekatze commented on apps/app/src/components/UnlockStore.tsx
> +
this needs to be removed - see suggestion

2023-04-04 21:40 UTC, tarunsamanta2k20 commented on apps/app/src/components/UnlockStore.tsx
> +
Done

2023-04-04 22:01 UTC, thekatze requested changes
i have added linting to the main branch so theres no ambiguity about styling.
i hope the merge conflicts wont be too bad

please update from main :)

2023-04-04 22:55 UTC, tarunsamanta2k20 commented on apps/app/src/pages/EditEntry.tsx
> +              onClick={() => copyToClipBoard(password()!!)}
> 

Non-null assertion operator
A new ! post-fix expression operator may be used to assert that its operand is non-null and non-undefined in contexts where the type checker is unable to conclude that fact. Specifically, the operation x! Produces a value of the type of x with null and undefined excluded. Similar to type assertions of the forms <T>x and x as T, the! non-null assertion operator is simply removed in the emitted JavaScript code.

2023-05-23 17:38 UTC, tarunsamanta2k20 commented
@thekatze this PR has been opened since long time. Anything else do I have added to it?

2023-05-23 19:11 UTC, thekatze approved these changes
i have done the remaining changes to the pr myself.
looks good now :)

2023-05-23 19:12 UTC, merged